# Generated by Django 5.1.7 on 2025-03-11 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0002_alter_trainee_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainee',
            old_name='course',
            new_name='course_id',
        ),
    ]
